### PR TITLE
Be/init auth

### PR DESCRIPTION
**Pull request by jonathannicolasdev**

### CODE REVIEW

**Comment by jonathannicolasdev** [comment]
Please check the updated schema, I did the chat related models and updated the User model as well. IMPORTANT: pull down the changes made on this branch (i.e init_auth).

**Comment by LeonMoreno** [comment]
> @LeonMoreno Please check the updated schema, I did the chat related models and updated the User model as well. IMPORTANT: pull down the changes made on this branch (i.e init_auth).

How I explained it to you. Authentication is going to change. This branch is not yet ready to Merge.

Next time, make your changes in another branch, that's good practice. This way we can have the changes and the code well separated. I repeat, good practices.

**Review by LeonMoreno — COMMENTED** [review]
How I explained it to you. Authentication is going to change. This branch is not yet ready to Merge.

Next time, make your changes in another branch, that's good practice. This way we can have the changes and the code well separated. I repeat, good practices.

I prefer that you have another branch where you have these changes, not in the authentication branch.

The database schema, chat models have nothing to do with authentication. My friend!!

That's why I told you when I PULLed this branch... IT IS NOT READY TO MERGE YET!!!

**Comment by LeonMoreno** [comment]
I am in the middle of changing the authentication packages, they are changes that I have locally that are not ready yet. The authentication process is a neuralgic part.

You can PULL the database schema into another separate branch. I would only make a few small changes to the relationships... But we look at that in another BRANCH.

**Pull request closed without merging**
